import 'package:flutter/material.dart';
import '../../core/i18n.dart';
import '../../core/theme.dart';

/// كلمة من اللهجة السودانية: الكلمة، معناها بالفصحى، بالإنجليزي، مثال، التصنيف
class DWord {
  final String word, msa, en, ex, cat;
  const DWord(this.word, this.msa, this.en, this.ex, this.cat);
}

/// تصنيف كلمات اللهجة
class DCat {
  final String key, emoji, sd, ar, en;
  final Color color;
  const DCat(this.key, this.emoji, this.sd, this.ar, this.en, this.color);
  String get name => t(sd, ar, en);
}

const dialectCats = [
  DCat('greet', '🤝', 'السلام والتحايا', 'التحية', 'Greetings', SD.teal),
  DCat('words', '❓', 'كلمات السؤال والربط', 'أدوات وأسئلة', 'Little words', SD.nile),
  DCat('expr', '💬', 'تعابير', 'تعابير', 'Expressions', SD.purple),
  DCat('people', '👨‍👩‍👧', 'الأهل والناس', 'الأسرة والناس', 'Family & people', SD.henna),
  DCat('food', '🍲', 'الأكل والشراب', 'الطعام والشراب', 'Food & drink', SD.orange),
  DCat('home', '🏠', 'البيت', 'المنزل', 'Home', SD.indigo),
  DCat('feel', '😊', 'الحالة والوصف', 'المشاعر والصفات', 'Feelings & traits', SD.pink),
  DCat('verbs', '🏃', 'أفعال', 'أفعال', 'Verbs', SD.green),
  DCat('time', '⏰', 'الزمن', 'الوقت', 'Time', SD.gold),
  DCat('market', '🛒', 'السوق والقروش', 'السوق والمال', 'Market & money', SD.coffee),
  DCat('body', '🩺', 'الجسم والعيا', 'الجسم والصحة', 'Body & health', SD.red),
  DCat('nature', '🌿', 'الطبيعة والبهايم', 'الطبيعة والحيوان', 'Nature & animals', SD.green),
  DCat('culture', '🪘', 'العادات والمناسبات', 'العادات والمناسبات', 'Customs', SD.henna),
  DCat('clothes', '👘', 'اللبس', 'الملابس', 'Clothing', SD.indigo),
  DCat('travel', '🚌', 'المواصلات', 'المواصلات', 'Transport', SD.nile),
];

/// قاموس اللهجة السودانية (كلمات شائعة ومعروفة فقط)
const dialectWords = <DWord>[
  // ── التحايا ──
  DWord('كيفنك', 'كيف حالك؟', 'How are you?', 'كيفنك يا زول؟ طوّلت!', 'greet'),
  DWord('إزيك', 'كيف حالك؟', 'How are you? (hi)', 'إزيك يا خالتو، إن شاء الله طيبة؟', 'greet'),
  DWord('عامل كيف', 'كيف حالك؟', 'How are you doing?', 'عامل كيف مع الشغل الجديد؟', 'greet'),
  DWord('كيف الحال', 'كيف الحال؟', 'How is everything?', 'السلام عليكم، كيف الحال؟', 'greet'),
  DWord('سلامات', 'السلام / مرحبًا', 'Hello (warm greeting)', 'سلامات يا جماعة!', 'greet'),
  DWord('حبابك', 'مرحبًا بك', 'Welcome!', 'حبابك، اتفضل أقعد.', 'greet'),
  DWord('حبابك عشرة', 'أهلًا وسهلًا بك كثيرًا', 'A very warm welcome', 'حبابك عشرة، البيت بيتك.', 'greet'),
  DWord('مرحب بيك', 'مرحبًا بك', 'You are welcome here', 'مرحب بيك في حلتنا.', 'greet'),
  DWord('أهلين', 'أهلًا', 'Hi / welcome', 'أهلين، اتفضلوا جوّه.', 'greet'),
  DWord('تمام', 'بخير / حسنًا', 'Fine / OK', 'أنا تمام الحمد لله.', 'greet'),
  DWord('كويس', 'جيد / بخير', 'Good / fine', 'الحمد لله كويس، وإنت؟', 'greet'),
  DWord('كتّر خيرك', 'شكرًا لك (أكثر الله خيرك)', 'Thank you (lit. may God increase your good)', 'كتّر خيرك على الوقفة دي.', 'greet'),
  DWord('يديك العافية', 'يعطيك العافية', 'Thank you / God give you health', 'يديك العافية يا عمك.', 'greet'),
  DWord('عفيت منك', 'أحسنت / شكرًا لك', 'Well done / thank you', 'عفيت منك، الشغل بقى سمح.', 'greet'),
  DWord('معليش', 'عذرًا / لا بأس', 'Sorry / never mind', 'معليش اتأخرت عليك.', 'greet'),
  DWord('مع السلامة', 'مع السلامة', 'Goodbye', 'مع السلامة، وصّل سلامي للأهل.', 'greet'),
  DWord('في أمان الله', 'في حفظ الله', 'Go safely (goodbye)', 'يلا، في أمان الله.', 'greet'),
  DWord('تصبح على خير', 'تصبح على خير', 'Good night', 'تصبح على خير، نتلاقى بكرة.', 'greet'),
  DWord('صباح الخير', 'صباح الخير', 'Good morning', 'صباح الخير يا حبوبة.', 'greet'),
  DWord('الله يخليك', 'أبقاك الله / من فضلك', 'Please / God keep you', 'الله يخليك ناولني الموية.', 'greet'),
  DWord('عامرة', 'دامت عامرة (تُقال بعد الأكل)', 'May your table always be full (said after a meal)', 'الأكل سمح شديد، عامرة إن شاء الله.', 'greet'),
  DWord('البركة فيكم', 'عظّم الله أجركم (تعزية)', 'My condolences (lit. blessing is in you)', 'البركة فيكم، الله يرحمو.', 'greet'),

  // ── أدوات وأسئلة ──
  DWord('شنو', 'ماذا / ما', 'What', 'اسمك شنو؟', 'words'),
  DWord('منو', 'مَن', 'Who', 'منو الدقّ الباب؟', 'words'),
  DWord('وين', 'أين', 'Where', 'إنت وين هسي؟', 'words'),
  DWord('متين', 'متى', 'When (question)', 'حتجي متين؟', 'words'),
  DWord('كيفن', 'كيف', 'How', 'دي بتتعمل كيفن؟', 'words'),
  DWord('ليه', 'لماذا', 'Why', 'ليه ما جيت أمس؟', 'words'),
  DWord('ياتو', 'أيّ / أيّهم', 'Which (one)', 'ياتو واحد داير؟', 'words'),
  DWord('مالك', 'ما بك؟', 'What\'s wrong with you?', 'مالك زعلان الليلة؟', 'words'),
  DWord('كدا', 'هكذا / كذلك', 'Like this / so', 'أعملها كدا وخلاص.', 'words'),
  DWord('هسي', 'الآن', 'Now', 'تعال هسي طوالي.', 'words'),
  DWord('دا', 'هذا', 'This (masc.)', 'دا بيتنا.', 'words'),
  DWord('دي', 'هذه', 'This (fem.)', 'دي أختي الكبيرة.', 'words'),
  DWord('ديل', 'هؤلاء', 'These', 'ديل أولاد خالي.', 'words'),
  DWord('داك', 'ذلك', 'That (masc.)', 'العربية داك حقت منو؟', 'words'),
  DWord('ديك', 'تلك', 'That (fem.)', 'الشدرة ديك كبيرة شديد.', 'words'),
  DWord('ساي', 'فقط / بلا سبب', 'Just / for nothing', 'قاعد ساي، ما عندي شغلة.', 'words'),
  DWord('ساكت', 'فقط / مجرد', 'Just / merely', 'دا كلام ساكت ما تصدقو.', 'words'),
  DWord('بس', 'فقط / يكفي', 'Only / enough', 'داير موية بس.', 'words'),
  DWord('عديل', 'مباشرة / تمامًا', 'Straight / directly / totally', 'أمشي عديل وبتلقى الدكان.', 'words'),
  DWord('تب', 'أبدًا / إطلاقًا', 'Never / not at all', 'ما بجيك تاني تب.', 'words'),
  DWord('برضو', 'أيضًا', 'Also / too', 'أنا برضو ماشي معاكم.', 'words'),
  DWord('كمان', 'أيضًا / كذلك', 'Also / more', 'داير شاي كمان.', 'words'),
  DWord('لسه', 'بَعدُ / ما زال', 'Still / not yet', 'لسه ما وصل.', 'words'),
  DWord('شديد', 'جدًّا', 'Very', 'الجو حار شديد الليلة.', 'words'),
  DWord('خالص', 'تمامًا / نهائيًّا', 'Completely / at all', 'نسيتو خالص.', 'words'),
  DWord('شوية', 'قليلًا', 'A little', 'استنى شوية.', 'words'),
  DWord('حبة', 'قليلًا / لحظة', 'A bit / a moment', 'أقعد حبة نتونّس.', 'words'),
  DWord('زي', 'مثل', 'Like / as', 'هو زي أبوه بالضبط.', 'words'),
  DWord('عشان', 'لأنّ / لكي', 'Because / so that', 'جيت بدري عشان ألحق.', 'words'),
  DWord('لمن', 'عندما', 'When (not a question)', 'لمن تصل كلمني.', 'words'),
  DWord('لحدي', 'حتى / إلى', 'Until / up to', 'أستناك لحدي المغرب.', 'words'),
  DWord('ولا', 'أو / أم', 'Or', 'شاي ولا جبنة؟', 'words'),
  DWord('بتاع', 'خاص بـ / ملك', 'Belonging to / of', 'الشنطة دي بتاعتي.', 'words'),
  DWord('حق', 'ملك / خاص بـ', 'Belonging to', 'الموبايل دا حقي.', 'words'),
  DWord('زاتو', 'ذاته / نفسه', 'Itself / the same', 'هو زاتو ما عارف.', 'words'),
  DWord('ياهو', 'هو ذاته / ها هو', 'That\'s the one / there it is', 'ياهو دا الزول الكلمتك عليهو.', 'words'),
  DWord('قاعد', 'يفعل الآن (للاستمرار)', 'Is …-ing (ongoing action)', 'قاعد أكتب في الواجب.', 'words'),
  DWord('ح / حا', 'سوف', 'Will (future)', 'حامشي السوق بعد شوية.', 'words'),
  DWord('برا', 'خارج', 'Outside', 'الشفع بلعبوا برا.', 'words'),
  DWord('جوّه', 'داخل', 'Inside', 'أدخل جوّه من الحر.', 'words'),
  DWord('قدّام', 'أمام', 'In front of', 'العربية واقفة قدّام البيت.', 'words'),
  DWord('ورا', 'خلف / وراء', 'Behind', 'الدكان ورا الجامع.', 'words'),
  DWord('جنب', 'بجانب', 'Next to', 'أقعد جنبي.', 'words'),
  DWord('هوي', 'يا هذا (نداء)', 'Hey you! (calling someone)', 'هوي! تعال هنا.', 'words'),
  DWord('آي', 'نعم', 'Yes', 'آي، أنا جاهز.', 'words'),
  DWord('أيوة', 'نعم', 'Yes', 'أيوة، فهمتك.', 'words'),
  DWord('أها', 'إذن / حسنًا', 'So… / OK then', 'أها، وبعداك حصل شنو؟', 'words'),

  // ── تعابير ──
  DWord('ياخ', 'يا أخي', 'Man! / dude', 'ياخ خليك من الكلام دا.', 'expr'),
  DWord('يا زول', 'يا رجل / يا صاحبي', 'Hey man', 'يا زول إنت وين من زمان؟', 'expr'),
  DWord('زول', 'شخص / إنسان', 'Person / guy', 'الزول دا طيب شديد.', 'expr'),
  DWord('زولي', 'صديقي', 'My buddy / my friend', 'دا زولي من أيام المدرسة.', 'expr'),
  DWord('داير', 'أريد', 'I want / wants', 'داير أشرب شاي.', 'expr'),
  DWord('ما في', 'لا يوجد', 'There isn\'t / none', 'ما في كهربا من الصباح.', 'expr'),
  DWord('في', 'يوجد', 'There is', 'في موية في التلاجة.', 'expr'),
  DWord('ما في عوجة', 'لا مشكلة', 'No problem', 'ما في عوجة، بنلحق.', 'expr'),
  DWord('عوجة', 'مشكلة', 'Problem / trouble', 'العوجة شنو؟', 'expr'),
  DWord('قدر ظروفك', 'على قدر استطاعتك', 'Within your means', 'أعمل قدر ظروفك، ما تتكلف.', 'expr'),
  DWord('كدي', 'دعني / لحظة', 'Let me… / hold on', 'كدي أشوف الموضوع دا.', 'expr'),
  DWord('غايتو', 'على كلٍّ / المهم', 'Anyway / well', 'غايتو، الله يسهّل.', 'expr'),
  DWord('يا دوب', 'بالكاد / للتوّ', 'Barely / just now', 'يا دوب وصلت البيت.', 'expr'),
  DWord('سجمي', 'يا للمصيبة!', 'Oh no! (lament)', 'سجمي! الأكل اتحرق.', 'expr'),
  DWord('حليل', 'ما أجمل ذكرى… (حنين)', 'How I miss…', 'حليل زمن الدراسة.', 'expr'),
  DWord('حرّم', 'أقسم (والله)', 'I swear', 'حرّم ما شفتو.', 'expr'),
  DWord('بالله؟', 'حقًّا؟', 'Really?', 'بالله؟ نجح؟', 'expr'),
  DWord('بالجد', 'حقًّا / بجدية', 'Seriously', 'بالجد، الكلام دا صاح.', 'expr'),
  DWord('ما تشيل هم', 'لا تهتمّ / لا تقلق', 'Don\'t worry', 'ما تشيل هم، أنا معاك.', 'expr'),
  DWord('أبشر', 'أبشر / حاضر', 'Sure / consider it done', 'أبشر، بكرة بجيبها ليك.', 'expr'),
  DWord('ربنا يسهّل', 'يسّر الله', 'God willing it goes well', 'ربنا يسهّل أمورك.', 'expr'),
  DWord('الله كريم', 'الله كريم', 'God is generous (it\'ll be fine)', 'الحال صعب لكن الله كريم.', 'expr'),
  DWord('شلاقة', 'تدخّل فيما لا يعني', 'Meddling / nosiness', 'دي شلاقة، خليك في حالك.', 'expr'),
  DWord('شفقة', 'استعجال / لهفة', 'Hurry / impatience', 'ما تعمل شفقة، الأمور بتمشي.', 'expr'),
  DWord('قوة عين', 'جرأة / وقاحة', 'Nerve / cheek', 'دي قوة عين منو!', 'expr'),
  DWord('دقس', 'أخطأ / غفل', 'Messed up / was fooled', 'دقست ونسيت المفتاح جوّه.', 'expr'),
  DWord('ما بعرف', 'لا أعرف', 'I don\'t know', 'والله ما بعرف الطريق.', 'expr'),

  // ── الأهل والناس ──
  DWord('حبوبة', 'الجدّة', 'Grandmother', 'حبوبتي بتحكي أحلى حجوة.', 'people'),
  DWord('جدو', 'الجدّ', 'Grandfather', 'جدو قاعد في البرندة.', 'people'),
  DWord('أبوي', 'أبي', 'My father', 'أبوي مسافر الخرطوم.', 'people'),
  DWord('أمي', 'أمّي', 'My mother', 'أمي عملت عصيدة.', 'people'),
  DWord('أخوي', 'أخي', 'My brother', 'أخوي الكبير مغترب.', 'people'),
  DWord('ود', 'ابن', 'Son (of)', 'دا ود عمي.', 'people'),
  DWord('بت', 'بنت', 'Girl / daughter', 'البت دي شاطرة شديد.', 'people'),
  DWord('شافع', 'طفل', 'Child / kid', 'الشافع دا ود منو؟', 'people'),
  DWord('شفع', 'أطفال', 'Kids', 'الشفع مشوا المدرسة.', 'people'),
  DWord('جنا', 'ولد / طفل', 'Child', 'جناها لسه صغير.', 'people'),
  DWord('وليد', 'ولد صغير', 'Little boy', 'الوليد دا بيقرا وين؟', 'people'),
  DWord('راجل', 'زوج / رجل', 'Husband / man', 'راجلها شغال في السعودية.', 'people'),
  DWord('مرة', 'زوجة / امرأة', 'Wife / woman', 'مرتو من ناس كسلا.', 'people'),
  DWord('نسيب', 'صهر / قريب بالمصاهرة', 'In-law', 'نسيبي جانا الليلة.', 'people'),
  DWord('ناس', 'أهل / جماعة', 'Family / folks of', 'ناس أحمد مسافرين.', 'people'),
  DWord('رجّالة', 'رجال', 'Men', 'الرجّالة قاعدين في الضرا.', 'people'),
  DWord('نسوان', 'نساء', 'Women', 'النسوان مشن العرس.', 'people'),
  DWord('زولة', 'امرأة / شخص (مؤنث)', 'Woman / person (fem.)', 'الزولة دي جارتنا.', 'people'),
  DWord('دفعتي', 'زميلي في الدراسة', 'My classmate (same year)', 'دا دفعتي في الجامعة.', 'people'),
  DWord('عزّابي', 'أعزب', 'Bachelor', 'لسه عزّابي، ما عرّس.', 'people'),
  DWord('خواجة', 'أجنبي (أوروبي)', 'Foreigner (Westerner)', 'الخواجة دا بيتكلم عربي.', 'people'),
  DWord('ود البلد', 'ابن البلد الأصيل', 'A true local / decent guy', 'دا ود بلد بيقيف معاك.', 'people'),
  DWord('ست البيت', 'ربّة المنزل', 'Lady of the house', 'ست البيت عملت لينا غدا.', 'people'),
  DWord('ست الشاي', 'بائعة الشاي', 'Tea lady (street tea seller)', 'نشرب شاي عند ست الشاي.', 'people'),
  DWord('سيد الدكان', 'صاحب الدكان', 'Shop owner', 'سيد الدكان قال الرز خلص.', 'people'),
  DWord('فكي', 'معلّم القرآن / شيخ الخلوة', 'Qur\'an teacher (village sheikh)', 'الفكي بيحفّظ الحيران.', 'people'),
  DWord('حيران', 'طلاب الخلوة', 'Qur\'an school pupils', 'الحيران قاعدين بالألواح.', 'people'),
  DWord('عمدة', 'زعيم القرية', 'Village head', 'العمدة حل المشكلة.', 'people'),
  DWord('حاجة', 'امرأة كبيرة (لقب احترام)', 'Respected elderly woman', 'الحاجة دي جارتنا من زمان.', 'people'),
  DWord('عمك', 'لقب احترام للرجل الكبير', 'Uncle (respectful address)', 'يا عمك، الموقف وين؟', 'people'),
  DWord('مغترب', 'مقيم خارج بلده للعمل', 'Expat (working abroad)', 'أخوي مغترب في قطر.', 'people'),
  DWord('صاحبي', 'صديقي', 'My friend', 'صاحبي جاني من بدري.', 'people'),

  // ── الأكل والشراب ──
  DWord('الجبنة', 'القهوة السودانية وطقسها', 'Sudanese coffee (pot & ceremony)', 'العصر نقعد على الجبنة.', 'food'),
  DWord('ملاح', 'إدام / مرق يؤكل مع الكسرة', 'Stew (eaten with kisra)', 'الملاح الليلة ويكة.', 'food'),
  DWord('كسرة', 'خبز رقيق من دقيق الذرة', 'Thin sorghum flatbread', 'الكسرة مع ملاح الروب سمحة.', 'food'),
  DWord('عصيدة', 'عجينة سميكة من الدقيق تؤكل بالملاح', 'Thick porridge (eaten with stew)', 'عصيدة بملاح التقلية.', 'food'),
  DWord('قراصة', 'خبز سميك من القمح', 'Thick wheat flatbread', 'القراصة بالدمعة أكلة الشمالية.', 'food'),
  DWord('ويكة', 'بامية مجففة مطحونة', 'Dried ground okra', 'ملاح الويكة جاهز.', 'food'),
  DWord('تقلية', 'ملاح بلحم مجفف وويكة', 'Stew of dried meat & okra', 'التقلية بتتاكل مع العصيدة.', 'food'),
  DWord('شية', 'لحم مشوي', 'Grilled meat', 'الجمعة عاملين شية.', 'food'),
  DWord('مرارة', 'أكلة من كبدة ومعدة نيئة بالبهارات', 'Raw offal dish (liver & tripe)', 'المرارة بيعملوها يوم الضبيحة.', 'food'),
  DWord('كمونية', 'كرشة مطبوخة بالبهارات', 'Spiced cooked tripe', 'الكمونية بالكسرة لذيذة.', 'food'),
  DWord('بوش', 'خبز مفتّت بالفول', 'Bread mashed with fava beans', 'بوش الفطور جاهز.', 'food'),
  DWord('فول', 'فول مدمّس', 'Stewed fava beans', 'الفول بالزيت والجبنة.', 'food'),
  DWord('طعمية', 'فلافل', 'Falafel', 'رغيفة طعمية بالشطة.', 'food'),
  DWord('آبري', 'رقائق ذرة مخمّرة يُصنع منها مشروب', 'Fermented sorghum flakes (drink)', 'الآبري ما بيفارق مويدة رمضان.', 'food'),
  DWord('حلو مر', 'مشروب الآبري الأحمر في رمضان', 'Hulu-mur Ramadan drink', 'حلو مر بارد بعد الفطور.', 'food'),
  DWord('عرديب', 'التمر الهندي (مشروب)', 'Tamarind (drink)', 'عصير عرديب بارد.', 'food'),
  DWord('كركدي', 'مشروب الكركديه', 'Hibiscus drink', 'كركدي بارد في الحر.', 'food'),
  DWord('قنقليز', 'ثمر التبلدي', 'Baobab fruit', 'عصير القنقليز مفيد.', 'food'),
  DWord('قضيم', 'ثمر شجيرة القضيم (مشروب)', 'Gudaim berries (drink)', 'شربنا قضيم في السوق.', 'food'),
  DWord('دكوة', 'معجون الفول السوداني', 'Peanut paste', 'سلطة بالدكوة.', 'food'),
  DWord('شطة', 'فلفل حار', 'Hot chili', 'الفول بدون شطة ما بنفع.', 'food'),
  DWord('سلطة أسود', 'سلطة الباذنجان', 'Eggplant salad', 'سلطة أسود بالدكوة.', 'food'),
  DWord('بليلة', 'حبوب مسلوقة', 'Boiled grains / pulses', 'بليلة عدسية للفطور.', 'food'),
  DWord('لقيمات', 'كرات عجين مقلية', 'Fried dough balls', 'لقيمات مع الشاي.', 'food'),
  DWord('زلابية', 'عجين مقلي محلّى', 'Fried sweet dough', 'زلابية الصباح سخنة.', 'food'),
  DWord('رغيف', 'خبز', 'Bread (loaf)', 'جيب لينا رغيف من الفرن.', 'food'),
  DWord('موية', 'ماء', 'Water', 'أديني كباية موية.', 'food'),
  DWord('لبن', 'حليب', 'Milk', 'شاي باللبن لو سمحت.', 'food'),
  DWord('روب', 'لبن رائب', 'Yogurt / curdled milk', 'ملاح الروب سهل.', 'food'),
  DWord('فطور', 'وجبة الضحى (الإفطار)', 'Breakfast (mid-morning meal)', 'الفطور الساعة عشرة.', 'food'),
  DWord('غدا', 'الغداء', 'Lunch', 'الغدا بعد العصر.', 'food'),
  DWord('عشا', 'العشاء', 'Dinner', 'العشا خفيف الليلة.', 'food'),
  DWord('صينية', 'صحن كبير يجتمع عليه الناس للأكل', 'Shared meal tray', 'الصينية طلعت الضرا.', 'food'),
  DWord('مويدة', 'مائدة الإفطار (رمضان)', 'Iftar spread', 'المويدة جاهزة قبل المغرب.', 'food'),
  DWord('شاي سادة', 'شاي بدون حليب', 'Black tea', 'داير شاي سادة بسكر خفيف.', 'food'),
  DWord('جعان', 'جائع', 'Hungry', 'أنا جعان شديد.', 'food'),

  // ── البيت ──
  DWord('حوش', 'فناء البيت', 'Courtyard', 'الشفع بلعبوا في الحوش.', 'home'),
  DWord('راكوبة', 'مظلة من الخشب والقش', 'Shade shelter (wood & straw)', 'نقعد تحت الراكوبة.', 'home'),
  DWord('تكل', 'مطبخ تقليدي', 'Traditional kitchen hut', 'أمي في التكل بتعوس.', 'home'),
  DWord('عنقريب', 'سرير خشبي منسوج بالحبال', 'Rope-woven wooden bed', 'رقد في العنقريب برا.', 'home'),
  DWord('برش', 'حصير من السعف', 'Palm-leaf mat', 'فرشوا البرش للضيوف.', 'home'),
  DWord('بنبر', 'كرسي صغير منخفض', 'Low stool', 'أقعد في البنبر.', 'home'),
  DWord('زير', 'جرّة فخار للماء', 'Clay water jar', 'موية الزير باردة.', 'home'),
  DWord('قطية', 'كوخ دائري من القش', 'Round straw hut', 'القطية بتبرّد في الصيف.', 'home'),
  DWord('أوضة', 'غرفة', 'Room', 'أوضتي جوّه.', 'home'),
  DWord('برندة', 'رواق / شرفة', 'Veranda / porch', 'جدو قاعد في البرندة.', 'home'),
  DWord('حيطة', 'حائط', 'Wall', 'الحيطة دي محتاجة بوهية.', 'home'),
  DWord('شباك', 'نافذة', 'Window', 'أفتح الشباك.', 'home'),
  DWord('حَلّة', 'قِدر للطبخ', 'Cooking pot', 'الحَلّة في النار.', 'home'),
  DWord('كورة', 'وعاء / صحن كبير', 'Big bowl', 'العصيدة في الكورة.', 'home'),
  DWord('كباية', 'كوب', 'Cup / glass', 'أديني كباية شاي.', 'home'),
  DWord('كفتيرة', 'إبريق تسخين الماء والشاي', 'Kettle / teapot', 'الكفتيرة في النار.', 'home'),
  DWord('جك', 'إبريق ماء', 'Water jug', 'ملّي الجك موية.', 'home'),
  DWord('جردل', 'دلو', 'Bucket', 'جيب الجردل من الحمام.', 'home'),
  DWord('طشت', 'إناء كبير للغسيل', 'Wash basin', 'الغسيل في الطشت.', 'home'),
  DWord('منقد', 'موقد فحم', 'Charcoal stove', 'الجبنة على المنقد.', 'home'),
  DWord('كانون', 'موقد', 'Small stove', 'الكانون فيه فحم.', 'home'),
  DWord('مقشاشة', 'مكنسة', 'Broom', 'جيب المقشاشة نقش الحوش.', 'home'),
  DWord('ناموسية', 'شبكة الحماية من البعوض', 'Mosquito net', 'نوم بالناموسية في الخريف.', 'home'),
  DWord('ملاية', 'شرشف', 'Bedsheet', 'غيّر الملاية.', 'home'),
  DWord('مخدة', 'وسادة', 'Pillow', 'المخدة دي ناعمة.', 'home'),
  DWord('دولاب', 'خزانة الملابس', 'Wardrobe', 'الهدوم في الدولاب.', 'home'),
  DWord('تلاجة', 'ثلاجة', 'Fridge', 'الموية في التلاجة.', 'home'),
  DWord('مكيّف موية', 'مبرّد صحراوي', 'Evaporative (desert) cooler', 'ملّي مكيّف الموية.', 'home'),
  DWord('كوشة', 'مكبّ النفايات', 'Rubbish dump', 'ودّي الوسخ الكوشة.', 'home'),
  DWord('حِلّة', 'قرية / حيّ', 'Village / neighbourhood', 'حلتنا قريبة من البحر.', 'home'),
  DWord('فريق', 'حيّ', 'Neighbourhood quarter', 'فريقنا كلو أهل.', 'home'),
  DWord('البلد', 'القرية / مسقط الرأس', 'Hometown / home village', 'في العيد ماشين البلد.', 'home'),
  DWord('مُراح', 'حظيرة الماشية / القطيع', 'Livestock pen / herd', 'الغنم رجعت المراح.', 'home'),
  DWord('مسيد', 'مكان تحفيظ القرآن والذكر', 'Qur\'an school & mosque complex', 'الحيران في المسيد.', 'home'),
  DWord('خلوة', 'مدرسة قرآنية تقليدية', 'Traditional Qur\'an school', 'قرا في الخلوة وهو صغير.', 'home'),

  // ── الحالة والوصف ──
  DWord('زعلان', 'غاضب / حزين', 'Upset / angry', 'مالك زعلان مني؟', 'feel'),
  DWord('فرحان', 'فرِح', 'Happy', 'فرحان بالنجاح.', 'feel'),
  DWord('مبسوط', 'مسرور', 'Pleased / happy', 'مبسوط منك شديد.', 'feel'),
  DWord('مكيّف', 'مرتاح ومسرور', 'Content / in a great mood', 'بعد الجبنة بقيت مكيّف.', 'feel'),
  DWord('تعبان', 'متعب', 'Tired', 'تعبان من الشغل.', 'feel'),
  DWord('نعسان', 'نعِس', 'Sleepy', 'نعسان، حارقد بدري.', 'feel'),
  DWord('طفشان', 'ضجِر', 'Fed up / bored', 'طفشان من القعدة.', 'feel'),
  DWord('زهجان', 'متضايق / ضجِر', 'Annoyed / fed up', 'زهجان من الزحمة.', 'feel'),
  DWord('خلعان', 'خائف / مذعور', 'Frightened', 'الشافع خلعان من الكلب.', 'feel'),
  DWord('سمح', 'جميل / حسن', 'Nice / good / beautiful', 'الثوب دا سمح شديد.', 'feel'),
  DWord('حلو', 'جميل / لذيذ', 'Nice / sweet', 'الكلام دا حلو.', 'feel'),
  DWord('شين', 'قبيح / سيئ', 'Ugly / bad', 'الكلام الشين ما بنقولو.', 'feel'),
  DWord('كعب', 'سيئ', 'Bad', 'الشبكة كعبة الليلة.', 'feel'),
  DWord('نضيف', 'نظيف', 'Clean', 'البيت نضيف.', 'feel'),
  DWord('وسخان', 'متّسخ', 'Dirty', 'القميص وسخان.', 'feel'),
  DWord('رقيق', 'نحيف', 'Thin / slim', 'بقى رقيق بعد العيا.', 'feel'),
  DWord('تقيل', 'ثقيل', 'Heavy', 'الجوال دا تقيل.', 'feel'),
  DWord('شاطر', 'ماهر / ذكي', 'Clever / skilled', 'ولدك شاطر في القراية.', 'feel'),
  DWord('حريف', 'بارع / متقن', 'Expert / ace', 'حريف كورة.', 'feel'),
  DWord('غشيم', 'جاهل / ساذج', 'Naive / clueless', 'ما تبقى غشيم.', 'feel'),
  DWord('عوير', 'أحمق', 'Silly / foolish', 'ما تبقى عوير.', 'feel'),
  DWord('ملخبط', 'مرتبك / مشوّش', 'Confused / messy', 'الشغل دا ملخبط.', 'feel'),
  DWord('فاضي', 'غير مشغول / فارغ', 'Free / empty', 'إنت فاضي العصر؟', 'feel'),
  DWord('خربان', 'معطّل', 'Broken / out of order', 'المكيّف خربان.', 'feel'),
  DWord('مفلّس', 'لا يملك مالًا', 'Broke (no money)', 'آخر الشهر مفلّس عديل.', 'feel'),
  DWord('شفقان', 'قلِق / متلهّف', 'Anxious / eager', 'شفقان على نتيجة الامتحان.', 'feel'),
  DWord('عطشان', 'عطشان', 'Thirsty', 'عطشان، أديني موية.', 'feel'),

  // ── أفعال ──
  DWord('مشى', 'ذهب', 'Went', 'مشيت السوق الصباح.', 'verbs'),
  DWord('جا', 'جاء', 'Came', 'أبوي جا من السفر.', 'verbs'),
  DWord('قعد', 'جلس / بقي', 'Sat / stayed', 'قعدنا لحدي المغرب.', 'verbs'),
  DWord('شاف', 'رأى', 'Saw', 'شفتو في السوق.', 'verbs'),
  DWord('عاين', 'نظر', 'Looked', 'عاين هنا!', 'verbs'),
  DWord('كلّم', 'أخبر / حدّث', 'Told / spoke to', 'كلّمتو بالموضوع.', 'verbs'),
  DWord('شال', 'حمل / أخذ', 'Carried / took', 'شيل الشنطة دي معاك.', 'verbs'),
  DWord('ختّ', 'وضع', 'Put', 'ختّ المفتاح في التربيزة.', 'verbs'),
  DWord('جاب', 'أحضر', 'Brought', 'جيب لينا رغيف.', 'verbs'),
  DWord('ودّى', 'أوصل / أخذ إلى', 'Took (someone) to', 'وديني الموقف.', 'verbs'),
  DWord('لقى', 'وجد', 'Found', 'لقيت قروشي الضايعة.', 'verbs'),
  DWord('ضيّع', 'أضاع', 'Lost', 'ضيّعت الموبايل.', 'verbs'),
  DWord('قدر', 'استطاع', 'Could / was able', 'ما قدرت أجي.', 'verbs'),
  DWord('خلّى', 'ترك', 'Left / let', 'خليهو يرتاح.', 'verbs'),
  DWord('استنى', 'انتظر', 'Waited', 'استناني في المحطة.', 'verbs'),
  DWord('رقد', 'نام / استلقى', 'Lay down / slept', 'رقد بدري الليلة.', 'verbs'),
  DWord('صحى', 'استيقظ', 'Woke up', 'صحيت الفجر.', 'verbs'),
  DWord('بقى', 'صار', 'Became', 'بقى راجل كبير.', 'verbs'),
  DWord('زحّ', 'تنحّى / ابتعد قليلًا', 'Move over / step aside', 'زحّ شوية خليني أقعد.', 'verbs'),
  DWord('دفر', 'دفع', 'Pushed', 'دفرنا العربية لحدي ما دوّرت.', 'verbs'),
  DWord('جدع', 'رمى', 'Threw', 'أجدع الوسخ في الكوشة.', 'verbs'),
  DWord('كورك', 'صرخ / نادى بصوت عالٍ', 'Shouted', 'كورك عليهو من بعيد.', 'verbs'),
  DWord('فتّش', 'بحث', 'Searched / looked for', 'فتّشت المفتاح في كل حتة.', 'verbs'),
  DWord('دسّ', 'أخفى', 'Hid', 'دسّ الحلاوة من الشفع.', 'verbs'),
  DWord('زاغ', 'تهرّب / غاب', 'Skipped off / dodged', 'زاغ من المدرسة.', 'verbs'),
  DWord('قشّ', 'كنس', 'Swept', 'قشّي الحوش بدري.', 'verbs'),
  DWord('لمّ', 'جمع', 'Gathered / collected', 'لمّ الهدوم من الحبل.', 'verbs'),
  DWord('فرتق', 'فرّق / تفرّق', 'Broke up / dispersed', 'الناس فرتقت بعد العشا.', 'verbs'),
  DWord('اتلمّ', 'اجتمع', 'Got together', 'اتلمّينا في بيت جدو.', 'verbs'),
  DWord('اتونّس', 'تسامر / دردش', 'Chatted / hung out', 'اتونّسنا لحدي نص الليل.', 'verbs'),
  DWord('ونسة', 'حديث / سمر', 'Chat / small talk', 'الونسة حلوة مع الجبنة.', 'verbs'),
  DWord('انبسط', 'استمتع / سُرّ', 'Enjoyed', 'انبسطنا في العرس.', 'verbs'),
  DWord('كضب', 'كذب', 'Lied', 'ما تكضب عليّ.', 'verbs'),
  DWord('عزم', 'دعا (إلى طعام)', 'Invited', 'عزمنا على الغدا.', 'verbs'),
  DWord('ضرب تلفون', 'اتصل', 'Called (on the phone)', 'أضرب لي تلفون لمن تصل.', 'verbs'),
  DWord('نطّ', 'قفز', 'Jumped', 'الكديس نطّ من الحيطة.', 'verbs'),
  DWord('جرى', 'ركض', 'Ran', 'جرى عشان يلحق البص.', 'verbs'),
  DWord('اتشاكل', 'تشاجر', 'Quarrelled / fought', 'اتشاكلوا في الكورة.', 'verbs'),
  DWord('شكلة', 'شجار', 'A fight / quarrel', 'حصلت شكلة في السوق.', 'verbs'),
  DWord('دواس', 'عراك / ضرب', 'Brawl / fist fight', 'الشكلة قلبت دواس.', 'verbs'),
  DWord('عاس', 'خبز الكسرة على الصاج', 'Baked kisra (on the griddle)', 'أمي عاست الكسرة الصباح.', 'verbs'),
  DWord('عرّس', 'تزوّج', 'Got married', 'أخوي عرّس السنة الفاتت.', 'verbs'),

  // ── الوقت ──
  DWord('الليلة', 'اليوم', 'Today', 'الليلة الجمعة.', 'time'),
  DWord('أمبارح', 'أمس', 'Yesterday', 'جيت أمبارح بالليل.', 'time'),
  DWord('أول أمبارح', 'أول أمس', 'The day before yesterday', 'سافر أول أمبارح.', 'time'),
  DWord('بكرة', 'غدًا', 'Tomorrow', 'نتلاقى بكرة إن شاء الله.', 'time'),
  DWord('بعد بكرة', 'بعد غد', 'The day after tomorrow', 'الامتحان بعد بكرة.', 'time'),
  DWord('قُبّيل', 'قبل قليل', 'A moment ago', 'كان هنا قُبّيل.', 'time'),
  DWord('بعدين', 'لاحقًا', 'Later', 'بكلمك بعدين.', 'time'),
  DWord('طوالي', 'فورًا / مباشرة', 'Right away / straight', 'تعال طوالي.', 'time'),
  DWord('دغري', 'مباشرة / مستقيمًا', 'Straight away / straight on', 'أمشي دغري.', 'time'),
  DWord('بدري', 'مبكرًا', 'Early', 'صحيت بدري.', 'time'),
  DWord('ضحوية', 'وقت الضحى', 'Mid-morning', 'نجيكم ضحوية.', 'time'),
  DWord('عشية', 'المساء / آخر النهار', 'Late afternoon / evening', 'نتلاقى عشية.', 'time'),
  DWord('زمان', 'قديمًا', 'Long ago / in the old days', 'زمان كانت الحياة ساهلة.', 'time'),
  DWord('هسع', 'الآن', 'Now', 'هسع جاي.', 'time'),
  DWord('الواطة صبحت', 'طلع الصباح', 'Morning has come', 'قعدنا لحدي الواطة صبحت.', 'time'),
  DWord('السنة الفاتت', 'العام الماضي', 'Last year', 'السنة الفاتت مشينا البلد.', 'time'),
  DWord('الشهر الجاي', 'الشهر القادم', 'Next month', 'الإيجار الشهر الجاي.', 'time'),
  DWord('شوية شوية', 'تدريجيًّا / على مهل', 'Bit by bit / slowly', 'شوية شوية بتتعلم.', 'time'),
  DWord('بشيش', 'ببطء / بهدوء', 'Slowly / gently', 'سوق بشيش.', 'time'),

  // ── السوق والقروش ──
  DWord('قروش', 'نقود', 'Money', 'ما معاي قروش.', 'market'),
  DWord('فكّة', 'نقود صغيرة', 'Small change', 'عندك فكّة ألف؟', 'market'),
  DWord('الباقي', 'باقي النقود', 'Change (money back)', 'الباقي غلط.', 'market'),
  DWord('ماهية', 'راتب', 'Salary', 'الماهية لسه ما نزلت.', 'market'),
  DWord('مصروف', 'مصروف', 'Pocket money / allowance', 'أديتو مصروف المدرسة.', 'market'),
  DWord('شغلانة', 'عمل / وظيفة', 'Job / gig', 'لقيت شغلانة جديدة.', 'market'),
  DWord('عطالة', 'بطالة', 'Unemployment', 'العطالة كترت.', 'market'),
  DWord('دكان', 'متجر صغير', 'Corner shop', 'مشيت الدكان أجيب سكر.', 'market'),
  DWord('دلالة', 'مزاد', 'Auction market', 'اشترى العربية من الدلالة.', 'market'),
  DWord('سمسار', 'وسيط', 'Broker / middleman', 'السمسار لقى لينا بيت.', 'market'),
  DWord('رطل', 'وحدة وزن (نحو نصف كيلو)', 'Pound (weight unit ≈ 0.45 kg)', 'رطل سكر ورطل شاي.', 'market'),
  DWord('ملوة', 'مكيال للحبوب', 'Grain measure', 'ملوة عيش.', 'market'),
  DWord('كوم', 'كومة (بيع بالكوم)', 'A heap (sold by the heap)', 'كوم الطماطم بكم؟', 'market'),
  DWord('ربطة', 'حزمة', 'Bundle', 'ربطة جرجير.', 'market'),
  DWord('جوال', 'كيس كبير من الخيش', 'Big sack', 'جوال بصل.', 'market'),
  DWord('قفة', 'سلة', 'Basket', 'شيل القفة للسوق.', 'market'),
  DWord('قزازة', 'زجاجة', 'Bottle', 'قزازة موية.', 'market'),
  DWord('جركانة', 'وعاء بلاستيكي للسوائل', 'Jerrycan', 'جركانة زيت.', 'market'),
  DWord('غلا', 'غلاء', 'High prices', 'الغلا دا شديد.', 'market'),
  DWord('ترزي', 'خيّاط', 'Tailor', 'ودّيت الجلابية للترزي.', 'market'),
  DWord('بقالة', 'متجر مواد غذائية', 'Grocery', 'البقالة فاتحة لحدي نص الليل.', 'market'),
  DWord('طاحونة', 'مطحنة الحبوب', 'Grain mill', 'ودّي العيش الطاحونة.', 'market'),
  DWord('رصيد', 'رصيد الهاتف', 'Phone credit', 'حوّل لي رصيد.', 'market'),
  DWord('صندوق', 'جمعية ادخار دورية', 'Rotating savings group', 'دخلت صندوق مع ناس الشغل.', 'market'),
  DWord('كشف', 'مساهمة مالية جماعية لمناسبة', 'Group money collection (for an occasion)', 'عملنا كشف لعرس زميلنا.', 'market'),
  DWord('دين', 'دَين', 'Debt', 'عليّ دين للدكان.', 'market'),

  // ── الجسم والعيا ──
  DWord('عيان', 'مريض', 'Sick', 'أنا عيان من أمبارح.', 'body'),
  DWord('العيا', 'المرض', 'Illness', 'العيا خلاهو رقيق.', 'body'),
  DWord('سخانة', 'حُمّى / حرارة', 'Fever / heat', 'الشافع عندو سخانة.', 'body'),
  DWord('كحة', 'سعال', 'Cough', 'عندي كحة من البرد.', 'body'),
  DWord('نزلة', 'زكام / نزلة برد', 'Cold / flu', 'جاتني نزلة.', 'body'),
  DWord('برشامة', 'قرص دواء', 'Pill / tablet', 'أشرب البرشامة بعد الأكل.', 'body'),
  DWord('شفخانة', 'مستوصف', 'Clinic / dispensary', 'وديناهو الشفخانة.', 'body'),
  DWord('إسبتالية', 'مستشفى', 'Hospital', 'دخل الإسبتالية.', 'body'),
  DWord('أجزخانة', 'صيدلية', 'Pharmacy', 'الأجزخانة فاتحة؟', 'body'),
  DWord('كرعين', 'رجلان', 'Legs / feet', 'كرعيني واجعاني من المشي.', 'body'),
  DWord('خشم', 'فم', 'Mouth', 'أقفل خشمك وإنت بتاكل.', 'body'),
  DWord('إضان', 'أذن', 'Ear', 'إضاني بتوجعني.', 'body'),
  DWord('واجعني', 'يؤلمني', 'It hurts me', 'راسي واجعني.', 'body'),
  DWord('طهور', 'ختان', 'Circumcision', 'عملوا للوليد طهور.', 'body'),

  // ── الطبيعة والبهايم ──
  DWord('خريف', 'موسم الأمطار', 'Rainy season', 'الخريف السنة دي سمح.', 'nature'),
  DWord('مطرة', 'مطر', 'Rain (a shower)', 'المطرة صبّت الليل كلو.', 'nature'),
  DWord('هبوب', 'عاصفة ترابية', 'Dust storm (haboob)', 'الهبوب جات قفلوا الشبابيك.', 'nature'),
  DWord('كتّاحة', 'عاصفة غبار', 'Dust storm', 'الكتّاحة غطّت الحلة.', 'nature'),
  DWord('دميرة', 'موسم فيضان النيل', 'Nile flood season', 'في الدميرة البحر بيزيد.', 'nature'),
  DWord('البحر', 'النيل / النهر', 'The Nile (the river)', 'مشينا البحر العصر.', 'nature'),
  DWord('خلا', 'البرّية / الصحراء', 'Wilderness / open country', 'الإبل سارحة في الخلا.', 'nature'),
  DWord('رملة', 'رمل', 'Sand', 'الرملة حارة.', 'nature'),
  DWord('شدرة', 'شجرة', 'Tree', 'نقعد تحت الشدرة.', 'nature'),
  DWord('ضُل', 'ظل', 'Shade', 'أقعد في الضُل.', 'nature'),
  DWord('بهايم', 'ماشية', 'Livestock', 'البهايم في المراح.', 'nature'),
  DWord('غنماية', 'شاة / عنزة', 'A goat / sheep', 'الغنماية ولدت.', 'nature'),
  DWord('كديس', 'قط', 'Cat', 'الكديس أكل السمك.', 'nature'),
  DWord('دبيب', 'ثعبان', 'Snake', 'خلّي بالك، في دبيب.', 'nature'),
  DWord('جداد', 'دجاج', 'Chickens', 'الجداد في الحوش.', 'nature'),
  DWord('ضبان', 'ذباب', 'Flies', 'غطّي الأكل من الضبان.', 'nature'),
  DWord('ناموس', 'بعوض', 'Mosquitoes', 'الناموس كتير في الخريف.', 'nature'),
  DWord('نبق', 'ثمر السدر', 'Lote-tree (sidr) fruit', 'النبق حلو.', 'nature'),
  DWord('لالوب', 'ثمر الهجليج', 'Heglig (desert date) fruit', 'لالوب من السوق.', 'nature'),
  DWord('دوم', 'ثمر شجرة الدوم', 'Doum palm fruit', 'الدوم بيتنقع ويتشرب.', 'nature'),
  DWord('تبلدي', 'شجرة التبلدي (الباوباب)', 'Baobab tree', 'شدرة التبلدي ضخمة.', 'nature'),
  DWord('طلح', 'شجر الطلح', 'Talh acacia', 'دخان الطلح.', 'nature'),
  DWord('سنط', 'شجر السنط (القرض)', 'Sunt acacia', 'شجر السنط جنب البحر.', 'nature'),

  // ── العادات والمناسبات ──
  DWord('قريعتي راحت', 'لعبة أطفال شعبية في دائرة', 'Traditional circle game for kids', 'الشفع بلعبوا قريعتي راحت في الحوش.', 'culture'),
  DWord('سماية', 'حفل تسمية المولود', 'Baby-naming celebration', 'السماية يوم الجمعة.', 'culture'),
  DWord('جرتق', 'طقس من طقوس العرس السوداني', 'Jirtig wedding ritual', 'الجرتق بعد العقد.', 'culture'),
  DWord('حنّة', 'الحِنّاء', 'Henna', 'ليلة الحنّة للعروس.', 'culture'),
  DWord('دخان', 'تبخّر تقليدي بخشب الطلح', 'Traditional smoke bath (talh wood)', 'العروس قاعدة في الدخان.', 'culture'),
  DWord('دلكة', 'عجينة تجميل تقليدية', 'Traditional body scrub', 'الدلكة من تجهيزات العرس.', 'culture'),
  DWord('خُمرة', 'عطر سوداني تقليدي', 'Traditional Sudanese perfume', 'ريحة الخُمرة سمحة.', 'culture'),
  DWord('بخور', 'بخور', 'Incense', 'البخور في المبخر.', 'culture'),
  DWord('نفير', 'عمل جماعي تطوعي', 'Community self-help work', 'عملنا نفير نظفنا الحلة.', 'culture'),
  DWord('فزعة', 'نجدة جماعية', 'Rallying to help', 'الحلة كلها جات فزعة.', 'culture'),
  DWord('الضرا', 'مجلس رجال الحي للأكل', 'Men\'s communal eating spot', 'في رمضان الفطور في الضرا.', 'culture'),
  DWord('بيت البكا', 'بيت العزاء', 'House of mourning', 'مشينا بيت البكا.', 'culture'),
  DWord('الفاتحة', 'التعزية (قراءة الفاتحة)', 'Condolence visit', 'مشيت أرفع الفاتحة.', 'culture'),
  DWord('عرس', 'زواج / حفل زواج', 'Wedding', 'العرس الخميس الجاي.', 'culture'),
  DWord('لمّة', 'تجمّع', 'Get-together', 'لمّة الأهل في العيد.', 'culture'),
  DWord('قعدة', 'جلسة', 'Sit-down gathering', 'قعدة حلوة مع الصحاب.', 'culture'),
  DWord('حجوة', 'حكاية / قصة شعبية', 'Folk tale', 'حبوبة حكت لينا حجوة.', 'culture'),
  DWord('لوح', 'لوح خشبي للكتابة في الخلوة', 'Wooden writing board (Qur\'an school)', 'كتب الآية في اللوح.', 'culture'),

  // ── اللبس ──
  DWord('توب', 'ثوب نسائي سوداني', 'Sudanese women\'s wrap (toob)', 'لبست توب جديد للعرس.', 'clothes'),
  DWord('جلابية', 'جلباب', 'Jalabiya (long robe)', 'الجلابية البيضاء للجمعة.', 'clothes'),
  DWord('عمّة', 'عمامة', 'Turban', 'لفّ العمّة.', 'clothes'),
  DWord('طاقية', 'قلنسوة', 'Skullcap', 'الطاقية تحت العمّة.', 'clothes'),
  DWord('مركوب', 'حذاء جلدي تقليدي', 'Traditional leather shoes', 'المركوب الجلد للمناسبات.', 'clothes'),
  DWord('سفنجة', 'شبشب', 'Flip-flops', 'أمشي بالسفنجة.', 'clothes'),
  DWord('عراقي', 'قميص قطني تقليدي', 'Traditional cotton shirt', 'العراقي تحت الجلابية.', 'clothes'),
  DWord('سروال', 'سروال', 'Trousers / drawers', 'سروال طويل.', 'clothes'),
  DWord('طرحة', 'غطاء الرأس', 'Head scarf', 'طرحتها لونها أخضر.', 'clothes'),
  DWord('شال', 'وشاح', 'Shawl', 'شال على الكتف.', 'clothes'),
  DWord('هدوم', 'ملابس', 'Clothes', 'غسلت الهدوم.', 'clothes'),

  // ── المواصلات ──
  DWord('عربية', 'سيارة', 'Car', 'العربية في الورشة.', 'travel'),
  DWord('ركشة', 'مركبة بثلاث عجلات', 'Rickshaw (tuk-tuk)', 'ركبنا ركشة للسوق.', 'travel'),
  DWord('أمجاد', 'ميكروباص صغير للأجرة', 'Small minivan taxi', 'أمجاد للمطار.', 'travel'),
  DWord('هايس', 'حافلة صغيرة', 'Minibus', 'الهايس مليانة.', 'travel'),
  DWord('بص', 'حافلة', 'Bus', 'البص قام بدري.', 'travel'),
  DWord('لوري', 'شاحنة', 'Truck / lorry', 'اللوري شايل بضاعة.', 'travel'),
  DWord('كمساري', 'محصّل الأجرة', 'Bus conductor', 'أدّي الكمساري القروش.', 'travel'),
  DWord('موقف', 'محطة', 'Bus/taxi stand', 'استناني في الموقف.', 'travel'),
  DWord('مشوار', 'رحلة قصيرة / غرض', 'Errand / short trip', 'عندي مشوار صغير.', 'travel'),
  DWord('كبري', 'جسر', 'Bridge', 'الزحمة في الكبري.', 'travel'),
  DWord('زحمة', 'ازدحام', 'Traffic / crowd', 'الزحمة شديدة الصباح.', 'travel'),
  DWord('سوّاق', 'سائق', 'Driver', 'السوّاق ماشي سريع.', 'travel'),
  DWord('ورشة', 'ورشة تصليح', 'Garage / workshop', 'ودّيت العربية الورشة.', 'travel'),
  DWord('لِبَرّا', 'إلى الخارج / للسفر', 'Abroad', 'ماشي لِبَرّا للشغل.', 'travel'),
  DWord('تلفون', 'هاتف', 'Phone', 'تلفوني فاضي شحن.', 'travel'),
];
