import 'package:flutter/material.dart';
import '../../core/i18n.dart';
import '../../core/theme.dart';

/// مصطلح رسمي: الاسم بالعربي، المقابل الإنجليزي، الشرح، نصيحة، التصنيف
class OTerm {
  final String ar, en, expAr, expEn, tipAr, tipEn, cat;
  const OTerm(this.ar, this.en, this.expAr, this.expEn, this.tipAr, this.tipEn, this.cat);
  String get exp => isEn ? expEn : expAr;
  String get tip => isEn ? tipEn : tipAr;
}

class TCat {
  final String key, emoji, sd, ar, en;
  final Color color;
  const TCat(this.key, this.emoji, this.sd, this.ar, this.en, this.color);
  String get name => t(sd, ar, en);
}

const termCats = [
  TCat('gov', '🏛️', 'الحكومة والمعاملات', 'المعاملات الحكومية', 'Government', SD.nile),
  TCat('bank', '🏦', 'البنك', 'المصارف', 'Banking', SD.green),
  TCat('work', '💼', 'الشغل', 'العمل والتوظيف', 'Employment', SD.coffee),
  TCat('immig', '🛂', 'السفر والإقامة', 'الهجرة والإقامة', 'Immigration', SD.indigo),
  TCat('legal', '⚖️', 'قانوني', 'قانوني', 'Legal', SD.henna),
  TCat('medical', '🏥', 'إداري طبي', 'إداري طبي', 'Medical admin', SD.red),
];

const officialTerms = <OTerm>[
  // ── معاملات حكومية ──
  OTerm('استمارة', 'Form', 'نموذج رسمي مطبوع أو إلكتروني تُعبّأ فيه بياناتك لتقديم طلب.', 'An official printed or online form you fill in to apply for something.',
      'اكتب بخط واضح وطابق الاسم حرفيًا مع الجواز.', 'Write clearly and match your name exactly as in your passport.', 'gov'),
  OTerm('طلب', 'Application / Request', 'خطاب أو نموذج تطلب فيه خدمة أو إجراء من جهة رسمية.', 'A letter or form asking an authority for a service or action.',
      'احتفظ برقم الطلب أو الإيصال للمتابعة.', 'Keep the application number or receipt for follow-up.', 'gov'),
  OTerm('إقرار', 'Declaration / Acknowledgement', 'ورقة تعترف فيها بصحة معلومات أو بواقعة معيّنة وتتحمّل مسؤوليتها.', 'A signed statement confirming that certain information or facts are true.',
      'لا توقّع إقرارًا لا تفهم كل سطر فيه.', 'Never sign a declaration you don\'t fully understand.', 'gov'),
  OTerm('تعهّد', 'Undertaking / Pledge', 'التزام مكتوب بأن تفعل شيئًا أو تمتنع عنه مستقبلًا.', 'A written promise to do (or not do) something in the future.',
      'اقرأ العواقب المذكورة إذا خالفت التعهّد.', 'Check what happens if you break the undertaking.', 'gov'),
  OTerm('تفويض', 'Authorization', 'إذن مكتوب تسمح فيه لشخص آخر بإنجاز معاملة محددة نيابةً عنك.', 'Written permission letting someone else handle a specific task for you.',
      'حدّد المعاملة والمدة بدقة ولا تجعله مفتوحًا.', 'Name the exact task and time limit; don\'t leave it open-ended.', 'gov'),
  OTerm('توكيل', 'Power of attorney', 'وثيقة رسمية (غالبًا موثّقة) تمنح الوكيل صلاحية التصرّف باسمك؛ قد تكون عامة أو خاصة.', 'A formal (usually notarized) document giving an agent power to act in your name; general or specific.',
      'التوكيل العام خطير؛ فضّل الخاص بغرض محدد.', 'A general POA is risky; prefer a specific one.', 'legal'),
  OTerm('تصديق', 'Attestation / Legalization', 'ختم جهة رسمية (كالخارجية أو السفارة) يؤكد صحة توقيع أو ختم على وثيقة.', 'An official stamp (e.g. Foreign Ministry or embassy) confirming a signature or seal is genuine.',
      'بعض الدول تطلب تصديقات متسلسلة: الجهة المصدرة ثم الخارجية ثم السفارة.', 'Some countries need a chain: issuer, then Foreign Ministry, then embassy.', 'gov'),
  OTerm('توثيق', 'Notarization / Authentication', 'إثبات رسمي لمستند أو عقد أمام موثّق أو جهة مختصة ليصبح حجة رسمية.', 'Officially recording or certifying a document before a notary or authority.',
      'اسأل عن الرسوم وعدد النسخ المطلوبة مسبقًا.', 'Ask about fees and number of copies in advance.', 'legal'),
  OTerm('صورة طبق الأصل', 'Certified true copy', 'نسخة من مستند مختومة بما يفيد مطابقتها للأصل.', 'A copy stamped to confirm it matches the original.',
      'احمل الأصل معك؛ كثير من الجهات تطابقه بنفسها.', 'Bring the original; many offices compare it themselves.', 'gov'),
  OTerm('ترجمة معتمدة', 'Certified translation', 'ترجمة يقوم بها مترجم أو مكتب معتمد لدى الجهة المطلوبة وتُختم.', 'A translation by an accredited translator or office, stamped as official.',
      'تأكد أن الجهة تقبل المكتب المختار قبل الدفع.', 'Confirm the authority accepts that translation office before paying.', 'gov'),
  OTerm('شهادة حسن سير وسلوك', 'Certificate of good conduct', 'شهادة تفيد بعدم وجود سوابق جنائية على الشخص، تُطلب للتوظيف أو الإقامة.', 'A certificate stating you have no criminal record, often needed for jobs or residency.',
      'غالبًا لها مدة صلاحية قصيرة (مثل 3–6 أشهر)؛ استخرجها قرب موعد التقديم.', 'Often valid only a few months; get it close to when you apply.', 'gov'),
  OTerm('صحيفة الحالة الجنائية', 'Criminal record certificate (police clearance)', 'وثيقة من الشرطة أو الجهة المختصة تبيّن السجل الجنائي للشخص.', 'A police document showing a person\'s criminal record status.',
      'قد تحتاج تصديقها وترجمتها لاستخدامها خارج بلد الإصدار.', 'You may need it legalized and translated for use abroad.', 'gov'),
  OTerm('شهادة ميلاد', 'Birth certificate', 'وثيقة رسمية تثبت تاريخ ومكان الميلاد والوالدين.', 'Official record of date and place of birth and parents.',
      'احتفظ بنسخة إلكترونية ونسخ مصدّقة.', 'Keep a scan plus certified copies.', 'gov'),
  OTerm('الرقم الوطني', 'National ID number', 'رقم تعريف فريد يصدر للمواطن من السجل المدني.', 'A unique citizen identification number from the civil registry.',
      'لا تشاركه علنًا على وسائل التواصل.', 'Don\'t post it publicly on social media.', 'gov'),
  OTerm('السجل المدني', 'Civil registry', 'الجهة التي تسجّل المواليد والوفيات والزواج وتصدر الهوية.', 'The office that records births, deaths, marriages and issues IDs.',
      'حدّث بياناتك بعد الزواج أو المواليد الجدد.', 'Update your records after marriage or a new baby.', 'gov'),
  OTerm('إيصال', 'Receipt', 'ورقة تثبت دفع مبلغ أو استلام شيء.', 'Proof that money was paid or something was received.',
      'صوّر الإيصال فورًا فالحبر الحراري يبهت.', 'Photograph it right away — thermal ink fades.', 'gov'),
  OTerm('رسوم', 'Fees', 'مبالغ تُدفع مقابل خدمة حكومية أو إدارية.', 'Charges paid for a government or administrative service.',
      'ادفع عبر القنوات الرسمية فقط واحتفظ بالإيصال.', 'Pay only through official channels and keep the receipt.', 'gov'),
  OTerm('غرامة', 'Fine / Penalty', 'مبلغ يُفرض عند مخالفة نظام أو تأخير.', 'Money charged for breaking a rule or being late.',
      'تابع تواريخ التجديد لتتفادى غرامات التأخير.', 'Track renewal dates to avoid late fines.', 'gov'),
  OTerm('معاملة', 'Transaction / Paperwork case', 'إجراء رسمي تتابعه لدى جهة حكومية حتى إنجازه.', 'An official procedure you follow up with an authority until completed.',
      'دوّن رقم المعاملة واسم الموظف وتاريخ المراجعة.', 'Note the case number, clerk name and visit date.', 'gov'),
  OTerm('مراجعة', 'Follow-up visit', 'الحضور للجهة لمتابعة معاملة أو طلب.', 'Visiting an office to follow up on a case.',
      'احجز موعدًا مسبقًا إن كانت الخدمة تتطلب ذلك.', 'Book an appointment first if required.', 'gov'),
  OTerm('موعد', 'Appointment', 'وقت محدد مسبقًا لإنجاز خدمة.', 'A pre-booked time slot for a service.',
      'احضر قبل الموعد بوقت كافٍ ومعك كل الأوراق.', 'Arrive early with all documents.', 'gov'),
  OTerm('ختم', 'Stamp / Seal', 'علامة رسمية تُطبع على المستند لاعتماده.', 'An official mark that validates a document.',
      'تأكد أن الختم واضح وغير مقطوع.', 'Make sure the stamp is clear and complete.', 'gov'),
  OTerm('خطاب تعريف', 'Letter of introduction / To-whom-it-may-concern', 'خطاب من جهة عملك أو دراستك يعرّف بك وبوضعك.', 'A letter from your employer or school introducing you and your status.',
      'اطلب ذكر الراتب فقط إذا طلبته الجهة.', 'Ask them to include salary only if required.', 'work'),
  OTerm('خطاب عدم ممانعة', 'No-objection letter (NOC)', 'خطاب تؤكد فيه جهة (كصاحب العمل) أنها لا تعترض على إجراء معيّن.', 'A letter stating an entity (e.g. employer) has no objection to a certain action.',
      'تأكد من ذكر الغرض والمدة بوضوح.', 'Make sure the purpose and period are stated.', 'work'),
  OTerm('إخلاء طرف', 'Clearance', 'مستند يثبت أنك سلّمت العهد وسدّدت ما عليك قبل ترك عمل أو سكن.', 'Proof you returned items and settled dues before leaving a job or housing.',
      'لا تغادر قبل استلام إخلاء الطرف موقّعًا.', 'Don\'t leave before getting the signed clearance.', 'work'),
  OTerm('عهدة', 'Custody (company assets)', 'أدوات أو أجهزة سلّمها لك العمل وتكون مسؤولًا عنها.', 'Company items or devices issued to you that you are responsible for.',
      'اطلب كشفًا مكتوبًا بالعهدة عند الاستلام والتسليم.', 'Get a written list when receiving and returning them.', 'work'),

  // ── البنك ──
  OTerm('حساب جاري', 'Current account', 'حساب للمعاملات اليومية والسحب والإيداع، عادة بلا أرباح.', 'An everyday account for deposits and withdrawals, usually without interest.',
      'راجع رسوم الحساب الشهرية إن وُجدت.', 'Check for monthly account fees.', 'bank'),
  OTerm('حساب توفير', 'Savings account', 'حساب للادخار وقد تكون عليه قيود على السحب.', 'An account for saving; withdrawals may be limited.',
      'اسأل عن شروط السحب قبل الفتح.', 'Ask about withdrawal rules before opening.', 'bank'),
  OTerm('كشف حساب', 'Bank statement', 'بيان بكل الحركات على حسابك خلال فترة محددة.', 'A list of all transactions on your account over a period.',
      'السفارات تطلبه غالبًا لآخر 3–6 أشهر مختومًا.', 'Embassies often ask for 3–6 months, stamped.', 'bank'),
  OTerm('رصيد', 'Balance', 'المبلغ المتوفر في الحساب.', 'The amount available in the account.',
      'فرّق بين الرصيد الفعلي والمتاح (بعد الحجوزات).', 'Distinguish actual vs available balance (after holds).', 'bank'),
  OTerm('حوالة', 'Transfer / Remittance', 'إرسال مال من حساب أو مكان لآخر.', 'Sending money from one account or place to another.',
      'تأكد من اسم المستفيد ورقم الحساب حرفيًا.', 'Double-check the beneficiary name and account number.', 'bank'),
  OTerm('المستفيد', 'Beneficiary', 'الشخص أو الجهة التي تستلم الحوالة.', 'The person or entity receiving the transfer.',
      'احفظ بيانات المستفيد المعتمدة لتقليل الأخطاء.', 'Save verified beneficiaries to reduce errors.', 'bank'),
  OTerm('رقم الآيبان', 'IBAN', 'رقم حساب دولي موحّد يبدأ برمز الدولة ويُستخدم للتحويلات (في الدول التي تعتمده).', 'International Bank Account Number: starts with a country code; used for transfers where adopted.',
      'انسخه من تطبيق البنك بدل كتابته يدويًا.', 'Copy it from your bank app instead of typing it.', 'bank'),
  OTerm('رمز سويفت', 'SWIFT / BIC code', 'رمز من 8 أو 11 حرفًا يعرّف البنك في التحويلات الدولية.', 'An 8- or 11-character code identifying a bank for international transfers.',
      'يختلف أحيانًا بين الفروع؛ خذه من البنك نفسه.', 'It can differ by branch; get it from the bank itself.', 'bank'),
  OTerm('سعر الصرف', 'Exchange rate', 'قيمة عملة مقابل عملة أخرى.', 'The value of one currency against another.',
      'قارن السعر بعد الرسوم، لا السعر المعلن فقط.', 'Compare the rate after fees, not just the headline rate.', 'bank'),
  OTerm('عمولة', 'Commission / Fee', 'رسوم يأخذها البنك أو الصرافة على الخدمة.', 'A charge taken by a bank or exchange for a service.',
      'اسأل عن العمولة على الطرفين: المرسل والمستلم.', 'Ask about fees on both sending and receiving ends.', 'bank'),
  OTerm('إيداع', 'Deposit', 'وضع نقود في الحساب.', 'Putting money into an account.',
      'خذ إيصال الإيداع وتأكد من رقم الحساب.', 'Keep the deposit slip and verify the account number.', 'bank'),
  OTerm('سحب', 'Withdrawal', 'أخذ نقود من الحساب.', 'Taking money out of an account.',
      'انتبه لحد السحب اليومي.', 'Mind the daily withdrawal limit.', 'bank'),
  OTerm('الرقم السري', 'PIN', 'رقم سري للبطاقة لا يعرفه غيرك.', 'Your secret card number known only to you.',
      'البنك لن يطلبه منك أبدًا بالهاتف أو الرسائل.', 'Your bank will never ask for it by phone or message.', 'bank'),
  OTerm('رمز التحقق', 'OTP (one-time password)', 'رمز مؤقت يُرسل لهاتفك لتأكيد عملية.', 'A temporary code sent to your phone to confirm a transaction.',
      'لا تشاركه مع أي شخص حتى لو ادعى أنه من البنك.', 'Never share it, even with someone claiming to be the bank.', 'bank'),
  OTerm('بطاقة الخصم المباشر', 'Debit card', 'بطاقة تخصم مباشرة من رصيد حسابك.', 'A card that takes money directly from your account balance.',
      'فعّل إشعارات الحركات لكشف أي استخدام غريب.', 'Turn on transaction alerts to spot misuse.', 'bank'),
  OTerm('بطاقة ائتمان', 'Credit card', 'بطاقة تقترض بها من البنك وتسدد لاحقًا، وقد تترتب عليها فوائد أو رسوم.', 'A card that borrows from the bank, repaid later; may carry interest or fees.',
      'سدّد كامل المبلغ في موعده لتتجنب الرسوم.', 'Pay in full on time to avoid charges.', 'bank'),
  OTerm('شيك', 'Cheque', 'أمر مكتوب للبنك بدفع مبلغ لشخص معين.', 'A written order to a bank to pay a sum to someone.',
      'لا توقّع شيكًا على بياض.', 'Never sign a blank cheque.', 'bank'),
  OTerm('شيك مرتجع', 'Bounced cheque', 'شيك رفض البنك صرفه لعدم كفاية الرصيد أو خطأ.', 'A cheque the bank refused to pay (insufficient funds or error).',
      'قد يترتب عليه أثر قانوني في بعض الدول.', 'May have legal consequences in some countries.', 'bank'),
  OTerm('قرض', 'Loan', 'مبلغ تقترضه وتسدده على أقساط.', 'Money borrowed and repaid in instalments.',
      'احسب التكلفة الإجمالية لا القسط الشهري فقط.', 'Look at the total cost, not just the monthly payment.', 'bank'),
  OTerm('قسط', 'Instalment', 'جزء دوري من مبلغ يُسدّد على فترات.', 'A periodic part-payment of a total amount.',
      'اربط موعد القسط بيوم نزول الراتب.', 'Align the due date with payday.', 'bank'),
  OTerm('مرابحة', 'Murabaha (cost-plus sale)', 'صيغة تمويل إسلامية يشتري فيها البنك السلعة ويبيعها لك بربح معلوم وأقساط.', 'Islamic financing: the bank buys the item and sells it to you at a known markup in instalments.',
      'اطّلع على العقد ونسبة الربح وشروط السداد المبكر.', 'Read the contract, markup and early-payoff terms.', 'bank'),
  OTerm('تحويل راتب', 'Salary transfer', 'اشتراط بعض البنوك تحويل راتبك إليها لتقديم خدمات أو تمويل.', 'When a bank requires your salary to be paid into it for services or financing.',
      'اسأل عن شروط إلغاء تحويل الراتب.', 'Ask how to cancel the salary transfer later.', 'bank'),
  OTerm('اعرف عميلك', 'KYC (Know Your Customer)', 'إجراءات تحقق البنك من هويتك وبياناتك وتحديثها دوريًا.', 'Bank procedures to verify and periodically update your identity details.',
      'حدّث هويتك المنتهية لتجنب تجميد الحساب.', 'Update expired ID to avoid an account freeze.', 'bank'),
  OTerm('تجميد الحساب', 'Account freeze', 'إيقاف مؤقت للحركات على الحساب لسبب نظامي أو أمني.', 'A temporary block on account activity for legal or security reasons.',
      'راجع البنك مباشرة واطلب السبب كتابيًا.', 'Contact the bank directly and ask for the reason in writing.', 'bank'),
  OTerm('رسوم سنوية', 'Annual fee', 'مبلغ يُخصم سنويًا مقابل بطاقة أو خدمة.', 'A yearly charge for a card or service.',
      'تحقّق هل يمكن إعفاؤك منها بشروط.', 'Check if it can be waived under conditions.', 'bank'),

  // ── العمل ──
  OTerm('عقد عمل', 'Employment contract', 'اتفاق مكتوب بين العامل وصاحب العمل يحدد الوظيفة والأجر والمدة والحقوق.', 'A written agreement setting the job, pay, duration and rights.',
      'احتفظ بنسخة موقّعة وتأكد أنها بلغة تفهمها.', 'Keep a signed copy in a language you understand.', 'work'),
  OTerm('عقد محدد المدة', 'Fixed-term contract', 'عقد ينتهي في تاريخ محدد ما لم يُجدَّد.', 'A contract that ends on a set date unless renewed.',
      'دوّن تاريخ الانتهاء ومهلة الإشعار بالتجديد.', 'Note the end date and renewal notice period.', 'work'),
  OTerm('عقد غير محدد المدة', 'Open-ended contract', 'عقد مستمر بلا تاريخ انتهاء محدد.', 'A contract with no fixed end date.',
      'اعرف مدة الإشعار المطلوبة عند الاستقالة.', 'Know the notice period required to resign.', 'work'),
  OTerm('فترة تجربة', 'Probation period', 'مدة في بداية العمل لتقييم العامل؛ قد يجوز فيها إنهاء العقد بشروط أيسر.', 'An initial period to assess the employee; termination may be easier during it.',
      'تأكد من مدتها المكتوبة في العقد وفق نظام البلد.', 'Check its length in the contract and local law.', 'work'),
  OTerm('الراتب الأساسي', 'Basic salary', 'الأجر دون البدلات؛ تُحسب عليه غالبًا مكافأة نهاية الخدمة والتأمينات.', 'Pay before allowances; end-of-service and insurance are often based on it.',
      'انتبه إذا كان الأساسي صغيرًا والبدلات كبيرة.', 'Beware a low basic with large allowances.', 'work'),
  OTerm('بدل سكن', 'Housing allowance', 'مبلغ يُصرف للعامل لتغطية السكن.', 'Money paid to cover housing.',
      'تأكد هل يُصرف شهريًا أم مقدمًا.', 'Check if paid monthly or in advance.', 'work'),
  OTerm('بدل نقل', 'Transport allowance', 'مبلغ لتغطية المواصلات.', 'Money to cover transport.',
      'قد لا يُصرف إن وفّر العمل مواصلات.', 'May not apply if transport is provided.', 'work'),
  OTerm('عمل إضافي', 'Overtime', 'ساعات عمل فوق ساعات الدوام النظامية، ولها أجر إضافي غالبًا.', 'Hours beyond the normal schedule, usually paid extra.',
      'سجّل ساعاتك بنفسك يوميًا.', 'Keep your own daily log of hours.', 'work'),
  OTerm('إجازة سنوية', 'Annual leave', 'أيام إجازة مدفوعة يستحقها العامل كل سنة.', 'Paid days off earned each year.',
      'اطلبها كتابيًا واحتفظ بالموافقة.', 'Request in writing and keep the approval.', 'work'),
  OTerm('إجازة مرضية', 'Sick leave', 'غياب بسبب المرض بتقرير طبي معتمد.', 'Absence due to illness backed by an approved medical note.',
      'سلّم التقرير الطبي في وقته.', 'Submit the medical note on time.', 'work'),
  OTerm('استقالة', 'Resignation', 'إنهاء العامل للعقد بإرادته.', 'Ending the contract by the employee\'s choice.',
      'قدّمها كتابيًا واحتفظ بنسخة مؤرخة مستلمة.', 'Submit it in writing and keep a dated, received copy.', 'work'),
  OTerm('فترة الإشعار', 'Notice period', 'المدة الواجب إبلاغ الطرف الآخر بها قبل إنهاء العقد.', 'The time you must give before ending a contract.',
      'عدم الالتزام بها قد يُخصم من مستحقاتك.', 'Ignoring it may be deducted from your dues.', 'work'),
  OTerm('إنهاء خدمة', 'Termination', 'إنهاء العقد من جهة صاحب العمل.', 'Ending of the contract by the employer.',
      'اطلب سبب الإنهاء كتابيًا.', 'Ask for the reason in writing.', 'work'),
  OTerm('مكافأة نهاية الخدمة', 'End-of-service benefit (gratuity)', 'مبلغ يُستحق للعامل عند انتهاء علاقة العمل حسب مدة الخدمة والأجر ونظام البلد.', 'A payment due at the end of employment based on service length, wage and local law.',
      'جرّب حاسبة الراتب ونهاية الخدمة في التطبيق كتقدير.', 'Try the app\'s salary & end-of-service calculator for an estimate.', 'work'),
  OTerm('مخالصة', 'Final settlement / Release', 'ورقة تقرّ فيها باستلام كل مستحقاتك وإبراء ذمة صاحب العمل.', 'A document confirming you received all dues and release the employer.',
      'لا توقّعها قبل استلام المبلغ فعليًا ومراجعة الحساب.', 'Don\'t sign before actually receiving and checking the amount.', 'work'),
  OTerm('شهادة خبرة', 'Experience certificate', 'خطاب من صاحب العمل يثبت مدة عملك ووظيفتك.', 'A letter confirming your job title and period of employment.',
      'اطلبها قبل مغادرتك بوقت كافٍ.', 'Request it well before you leave.', 'work'),
  OTerm('مسير الرواتب', 'Payslip / Payroll', 'بيان يوضح تفاصيل راتبك والخصومات.', 'A statement showing your pay details and deductions.',
      'راجع الخصومات كل شهر.', 'Check deductions every month.', 'work'),
  OTerm('التأمينات الاجتماعية', 'Social insurance', 'نظام اشتراكات تُقتطع من الأجر لتأمين التقاعد أو الإصابة حسب نظام البلد.', 'Contributions deducted from pay for retirement or injury cover, per local law.',
      'تأكد أن صاحب العمل سجّلك بالراتب الصحيح.', 'Make sure your employer registered you at the correct wage.', 'work'),
  OTerm('إصابة عمل', 'Work injury', 'إصابة تحدث أثناء العمل أو بسببه.', 'An injury that happens at or because of work.',
      'أبلغ فورًا ووثّق الحادث بالتاريخ والشهود.', 'Report immediately and document it with date and witnesses.', 'work'),
  OTerm('السيرة الذاتية', 'CV / Résumé', 'ملخص مكتوب لمؤهلاتك وخبراتك.', 'A written summary of your qualifications and experience.',
      'جرّب أداة منشئ السيرة الذاتية في التطبيق.', 'Try the app\'s CV Builder tool.', 'work'),
  OTerm('خطاب عرض وظيفي', 'Job offer letter', 'عرض مكتوب بالوظيفة والراتب والمزايا قبل العقد.', 'A written offer stating role, pay and benefits before the contract.',
      'قارن العرض بالعقد النهائي بندًا بندًا.', 'Compare it with the final contract line by line.', 'work'),
  OTerm('مقابلة عمل', 'Job interview', 'لقاء لتقييم المتقدم للوظيفة.', 'A meeting to assess a job applicant.',
      'حضّر أمثلة واقعية من خبرتك.', 'Prepare real examples from your experience.', 'work'),
  OTerm('المسمى الوظيفي', 'Job title', 'اسم الوظيفة الرسمي.', 'The official name of your position.',
      'تأكد أن المسمى في العقد يطابق الإقامة/التأشيرة إن لزم.', 'Make sure it matches your visa/permit where required.', 'work'),
  OTerm('دوام', 'Working hours / Shift', 'الوقت المحدد للعمل يوميًا.', 'The set daily working time.',
      'اعرف أيام الراحة الأسبوعية المكتوبة.', 'Know your written weekly rest days.', 'work'),

  // ── الهجرة والإقامة ──
  OTerm('جواز سفر', 'Passport', 'وثيقة سفر رسمية تثبت الهوية والجنسية.', 'An official travel document proving identity and nationality.',
      'كثير من الدول تشترط صلاحية 6 أشهر على الأقل.', 'Many countries require at least 6 months\' validity.', 'immig'),
  OTerm('تأشيرة', 'Visa', 'إذن دخول إلى بلد لغرض ومدة محددين.', 'Permission to enter a country for a set purpose and period.',
      'تحقق من نوعها ومدتها وعدد السفرات المسموحة.', 'Check its type, duration and number of entries.', 'immig'),
  OTerm('تأشيرة خروج وعودة', 'Exit and re-entry visa', 'إذن للمقيم بالسفر ثم العودة خلال مدة محددة (معمول به في بعض الدول كالسعودية).', 'Permission for a resident to leave and return within a set period (used in some countries, e.g. Saudi Arabia).',
      'انتبه لتاريخ العودة؛ التأخر قد تكون له عواقب.', 'Mind the return deadline; overstaying abroad can have consequences.', 'immig'),
  OTerm('خروج نهائي', 'Final exit', 'تأشيرة مغادرة البلد نهائيًا وإلغاء الإقامة.', 'A visa to leave the country permanently, cancelling residency.',
      'سوِّ مستحقاتك وحساباتك قبل الإصدار.', 'Settle dues and accounts before it is issued.', 'immig'),
  OTerm('إقامة', 'Residence permit (Iqama)', 'تصريح يسمح للأجنبي بالإقامة في البلد لمدة محددة.', 'A permit allowing a foreigner to live in the country for a set period.',
      'سجّل تاريخ انتهائها في أداة الوثائق لتذكيرك.', 'Track its expiry in the app\'s Documents tool.', 'immig'),
  OTerm('كفيل', 'Sponsor', 'الجهة أو الشخص المسؤول نظاميًا عن إقامة العامل (في أنظمة الكفالة).', 'The person or company legally responsible for a worker\'s residency (in sponsorship systems).',
      'اعرف حقوقك وفق نظام البلد المحدّث.', 'Know your rights under current local rules.', 'immig'),
  OTerm('كفالة', 'Sponsorship / Guarantee', 'تحمّل المسؤولية النظامية عن شخص، أو ضمان التزام مالي لشخص آخر.', 'Legal responsibility for a person, or guaranteeing someone else\'s financial obligation.',
      'كفالة دين غيرك تجعلك ملزمًا بالسداد إن عجز.', 'Guaranteeing a debt makes you liable if they don\'t pay.', 'immig'),
  OTerm('نقل كفالة', 'Sponsorship transfer', 'تحويل إقامة العامل من صاحب عمل لآخر.', 'Moving a worker\'s residency from one employer to another.',
      'تأكد من الشروط وموافقة الجهات المختصة.', 'Check conditions and official approval.', 'immig'),
  OTerm('تأشيرة زيارة عائلية', 'Family visit visa', 'تأشيرة لزيارة الأقارب المقيمين.', 'A visa for relatives to visit a resident.',
      'جهّز إثبات القرابة مصدّقًا.', 'Prepare legalized proof of relationship.', 'immig'),
  OTerm('لمّ الشمل', 'Family reunification', 'إجراء يسمح لأفراد الأسرة بالانضمام لمقيم أو لاجئ.', 'A process allowing family members to join a resident or refugee.',
      'الشروط تختلف كثيرًا بين الدول؛ استشر جهة رسمية.', 'Rules vary widely; consult an official source.', 'immig'),
  OTerm('لاجئ', 'Refugee', 'شخص فرّ من بلده خوفًا من الاضطهاد أو النزاع ونال الحماية الدولية.', 'A person who fled persecution or conflict and has international protection.',
      'المفوضية السامية للأمم المتحدة لشؤون اللاجئين هي الجهة المرجعية.', 'UNHCR is the reference agency.', 'immig'),
  OTerm('طالب لجوء', 'Asylum seeker', 'شخص قدّم طلب حماية ولم يُبتّ فيه بعد.', 'Someone who applied for protection and awaits a decision.',
      'احتفظ بكل أوراق طلبك ومواعيدك.', 'Keep all your case papers and appointment dates.', 'immig'),
  OTerm('وثيقة سفر', 'Travel document', 'وثيقة تصدر بدل الجواز لبعض الفئات كاللاجئين.', 'A document issued instead of a passport to some groups such as refugees.',
      'تحقق من الدول التي تقبلها.', 'Check which countries accept it.', 'immig'),
  OTerm('تأشيرة عبور (ترانزيت)', 'Transit visa', 'إذن للمرور عبر بلد في الطريق لبلد آخر.', 'Permission to pass through a country en route elsewhere.',
      'بعض المطارات تشترطها حتى دون الخروج من المطار.', 'Some airports require it even airside.', 'immig'),
  OTerm('مخالفة الإقامة', 'Overstay', 'البقاء بعد انتهاء التأشيرة أو الإقامة.', 'Staying beyond your visa or permit expiry.',
      'قد يترتب عليها غرامات أو منع دخول.', 'May lead to fines or entry bans.', 'immig'),
  OTerm('القنصلية', 'Consulate', 'مكتب يقدّم خدمات للمواطنين في الخارج كالجوازات والتوثيق.', 'An office serving citizens abroad (passports, attestations).',
      'تحقّق من الموقع الرسمي للمواعيد والرسوم.', 'Use the official website for appointments and fees.', 'immig'),
  OTerm('السفارة', 'Embassy', 'التمثيل الدبلوماسي لدولة في دولة أخرى.', 'A country\'s diplomatic mission in another country.',
      'احذر الصفحات المزيفة التي تنتحل اسم السفارات.', 'Beware fake pages impersonating embassies.', 'immig'),
  OTerm('تصريح عمل', 'Work permit', 'إذن رسمي يسمح للأجنبي بالعمل.', 'Official permission for a foreigner to work.',
      'العمل بدونه قد يعرّضك للترحيل.', 'Working without one may lead to deportation.', 'immig'),
  OTerm('الفحص الطبي للإقامة', 'Residency medical exam', 'فحوصات تُطلب للحصول على تأشيرة أو إقامة.', 'Medical tests required for a visa or residency.',
      'اذهب فقط للمراكز المعتمدة رسميًا.', 'Use officially approved centres only.', 'immig'),
  OTerm('البصمة', 'Biometrics', 'تسجيل البصمات والصورة لدى الجهات الرسمية.', 'Recording fingerprints and photo with authorities.',
      'احجز الموعد مبكرًا في المواسم.', 'Book early during busy seasons.', 'immig'),

  // ── قانوني ──
  OTerm('عقد', 'Contract', 'اتفاق ملزم بين طرفين أو أكثر.', 'A binding agreement between two or more parties.',
      'لا توقّع على صفحات فارغة أو ناقصة.', 'Never sign blank or incomplete pages.', 'legal'),
  OTerm('بند', 'Clause', 'فقرة محددة في عقد أو نظام.', 'A specific section of a contract or law.',
      'اطلب تعديل البند غير الواضح قبل التوقيع.', 'Ask to amend unclear clauses before signing.', 'legal'),
  OTerm('شرط جزائي', 'Penalty clause', 'مبلغ يُدفع إذا أخلّ أحد الطرفين بالعقد.', 'An amount payable if a party breaches the contract.',
      'افهم متى يُطبق وكم قيمته.', 'Understand when it applies and how much it is.', 'legal'),
  OTerm('عقد إيجار', 'Lease agreement', 'عقد بين المالك والمستأجر يحدد الأجرة والمدة.', 'A contract between landlord and tenant setting rent and term.',
      'وثّقه في المنصة الرسمية إن كان البلد يشترط ذلك.', 'Register it on the official platform if required.', 'legal'),
  OTerm('تأمين (عربون/ضمان)', 'Security deposit', 'مبلغ يُدفع للمالك يُسترد عند تسليم السكن سليمًا.', 'Money paid to a landlord, refundable if the home is returned in good condition.',
      'صوّر حالة السكن يوم الاستلام.', 'Photograph the home\'s condition on move-in day.', 'legal'),
  OTerm('عربون', 'Down payment / Earnest money', 'مبلغ يُدفع لحجز صفقة، وقد لا يُسترد إذا تراجعت.', 'A payment to secure a deal; may be non-refundable if you back out.',
      'اكتب شروط استرداده في الإيصال.', 'Write refund terms on the receipt.', 'legal'),
  OTerm('مستند / سند', 'Instrument / Deed', 'ورقة رسمية تثبت حقًا أو التزامًا.', 'A formal paper proving a right or obligation.',
      'احفظ الأصل في مكان آمن ونسخة رقمية.', 'Keep the original safe plus a digital copy.', 'legal'),
  OTerm('صك', 'Title deed', 'وثيقة رسمية تثبت ملكية عقار.', 'An official document proving property ownership.',
      'تحقق من الصك لدى الجهة الرسمية قبل الشراء.', 'Verify the deed with the official registry before buying.', 'legal'),
  OTerm('شاهد', 'Witness', 'شخص يشهد على توقيع أو واقعة.', 'A person attesting to a signature or event.',
      'تأكد من بيانات هوية الشهود في العقد.', 'Make sure witnesses\' ID details are in the contract.', 'legal'),
  OTerm('دعوى', 'Lawsuit / Claim', 'طلب يُرفع للمحكمة للمطالبة بحق.', 'A case filed in court to claim a right.',
      'استشر محاميًا مرخّصًا قبل رفعها.', 'Consult a licensed lawyer before filing.', 'legal'),
  OTerm('بلاغ', 'Police report', 'إخطار رسمي للشرطة بحادث أو جريمة.', 'An official notification to police of an incident or crime.',
      'خذ رقم البلاغ؛ تحتاجه للتأمين أو بدل فاقد.', 'Get the report number — needed for insurance or replacements.', 'legal'),
  OTerm('بدل فاقد', 'Replacement (for lost document)', 'إصدار وثيقة جديدة بدل المفقودة.', 'Issuing a new document to replace a lost one.',
      'غالبًا يُطلب بلاغ فقدان أولًا.', 'A loss report is usually required first.', 'legal'),
  OTerm('حكم', 'Judgment / Ruling', 'قرار المحكمة في قضية.', 'A court\'s decision in a case.',
      'اعرف مهلة الاستئناف من تاريخ الحكم.', 'Know the appeal deadline from the ruling date.', 'legal'),
  OTerm('استئناف', 'Appeal', 'طلب مراجعة حكم أمام محكمة أعلى.', 'Asking a higher court to review a ruling.',
      'المهلة محددة بالأيام؛ لا تتأخر.', 'The deadline is short; don\'t delay.', 'legal'),
  OTerm('محامٍ', 'Lawyer', 'مختص مرخّص يمثلك أمام الجهات القضائية.', 'A licensed professional who represents you legally.',
      'تأكد من الترخيص واتفق على الأتعاب كتابيًا.', 'Verify the licence and agree fees in writing.', 'legal'),
  OTerm('أتعاب', 'Fees (professional)', 'أجر المحامي أو المستشار.', 'The fee of a lawyer or consultant.',
      'اطلب إيصالًا لكل دفعة.', 'Ask for a receipt for each payment.', 'legal'),
  OTerm('عقد زواج', 'Marriage contract', 'وثيقة رسمية تثبت الزواج.', 'An official document proving marriage.',
      'وثّقه وصدّقه لاستخدامه في الخارج.', 'Register and legalize it for use abroad.', 'legal'),
  OTerm('حصر ورثة', 'Inheritance determination (heirs list)', 'وثيقة قضائية تحدد الورثة الشرعيين.', 'A court document listing the legal heirs.',
      'تُطلب غالبًا لصرف أموال المتوفى من البنوك.', 'Often needed to release the deceased\'s bank funds.', 'legal'),
  OTerm('شهادة وفاة', 'Death certificate', 'وثيقة رسمية تثبت الوفاة وتاريخها.', 'Official proof of death and its date.',
      'استخرج عدة نسخ؛ تطلبها جهات كثيرة.', 'Get several copies; many offices need one.', 'legal'),
  OTerm('إعلان قانوني / إنذار', 'Legal notice', 'إخطار رسمي بمطالبة أو إجراء.', 'A formal notice of a claim or action.',
      'لا تتجاهله؛ قد تسري المهل من تاريخ استلامه.', 'Don\'t ignore it; deadlines may run from receipt.', 'legal'),
  OTerm('إبراء ذمة', 'Release from liability', 'إقرار بأن الطرف الآخر لم يعد مدينًا بشيء.', 'A statement that the other party owes nothing more.',
      'وقّعه فقط بعد التأكد من استلام كل حقوقك.', 'Sign only after receiving all your dues.', 'legal'),

  // ── إداري طبي ──
  OTerm('تقرير طبي', 'Medical report', 'وثيقة من الطبيب تشرح الحالة والتشخيص.', 'A doctor\'s document describing condition and diagnosis.',
      'اطلب نسخة مختومة لكل جهة تحتاجه.', 'Ask for a stamped copy for each office that needs it.', 'medical'),
  OTerm('إجازة مرضية معتمدة', 'Certified sick note', 'تقرير يوصي بعدد أيام راحة ويعتمد رسميًا.', 'A note recommending rest days, officially approved.',
      'بعض الدول تشترط إصدارها عبر منصة رسمية.', 'Some countries require issuance via an official platform.', 'medical'),
  OTerm('وصفة طبية (روشتة)', 'Prescription', 'ورقة الطبيب بالأدوية والجرعات.', 'The doctor\'s note of medicines and doses.',
      'احتفظ بها عند السفر بأدوية خاضعة للرقابة.', 'Carry it when travelling with controlled medicines.', 'medical'),
  OTerm('تأمين طبي', 'Health insurance', 'تغطية لتكاليف العلاج وفق وثيقة وشبكة محددة.', 'Coverage of treatment costs under a policy and network.',
      'اعرف الشبكة والمبالغ غير المغطاة.', 'Know the network and what isn\'t covered.', 'medical'),
  OTerm('نسبة التحمّل', 'Co-payment / Deductible', 'الجزء الذي تدفعه أنت من تكلفة العلاج.', 'The part of treatment costs you pay yourself.',
      'اسأل قبل الإجراء كم ستدفع.', 'Ask before the procedure how much you\'ll pay.', 'medical'),
  OTerm('موافقة مسبقة', 'Pre-approval', 'إذن من شركة التأمين قبل إجراء طبي.', 'Insurer authorization before a medical procedure.',
      'بدونها قد ترفض الشركة الدفع.', 'Without it the insurer may refuse to pay.', 'medical'),
  OTerm('الملف الطبي', 'Medical record', 'ملف يحوي تاريخك المرضي في المستشفى.', 'A file with your medical history at a hospital.',
      'يحق لك غالبًا طلب نسخة منه.', 'You can usually request a copy.', 'medical'),
  OTerm('خطاب تحويل', 'Referral letter', 'خطاب من طبيب يحوّلك لأخصائي أو مستشفى آخر.', 'A doctor\'s letter sending you to a specialist or another hospital.',
      'خذ معه نتائج التحاليل والأشعة.', 'Bring lab and imaging results with it.', 'medical'),
  OTerm('شهادة لياقة طبية', 'Medical fitness certificate', 'شهادة بأنك لائق صحيًا لعمل أو دراسة.', 'A certificate that you are medically fit for work or study.',
      'تأكد من الجهة المعتمدة لإصدارها.', 'Check which centre is approved to issue it.', 'medical'),
  OTerm('بطاقة التطعيم', 'Vaccination card', 'سجل التطعيمات الذي تأخذه.', 'A record of vaccines you have received.',
      'بعض الدول تطلب شهادة الحمى الصفراء الدولية للدخول.', 'Some countries require an international yellow fever certificate.', 'medical'),
  OTerm('موعد مراجعة', 'Follow-up appointment', 'موعد لاحق لمتابعة العلاج.', 'A later appointment to follow up on treatment.',
      'ضيفه لتقويمك فورًا.', 'Add it to your calendar right away.', 'medical'),
  OTerm('إقرار موافقة', 'Informed consent form', 'ورقة توافق فيها على إجراء طبي بعد شرح مخاطره.', 'A form agreeing to a procedure after its risks are explained.',
      'اسأل عن البدائل والمخاطر قبل التوقيع.', 'Ask about risks and alternatives before signing.', 'medical'),
  OTerm('تقرير خروج', 'Discharge summary', 'ملخص حالتك وعلاجك عند الخروج من المستشفى.', 'A summary of your condition and treatment at discharge.',
      'احتفظ به لطبيبك القادم.', 'Keep it for your next doctor.', 'medical'),
];
