// Generates supabase/seed.sql from the JSON data files so the SQL seed can
// never drift from the client data. Run: node scripts/generate-seed.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const characters = JSON.parse(readFileSync(join(root, 'src', 'data', 'characters.json'), 'utf8'));
const questions = JSON.parse(readFileSync(join(root, 'src', 'data', 'questions.json'), 'utf8'));

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

const characterRows = characters.map((c) => `  (${[
  c.id, q(c.slug), q(c.name), q(c.gender), q(c.profession), q(c.professionAr), q(c.field),
  q(c.skinTone), q(c.hairColor), q(c.hairLength), q(c.hairStyle), c.hasGlasses, q(c.beardStyle),
  q(c.headwear), q(c.clothing), c.uniform, q(c.accessory), c.worksInOffice, c.worksOutdoors,
  q(c.accent), q(c.visualTraits), q(`/assets/characters/${c.slug}.svg`), true,
].join(', ')})`).join(',\n');

const questionRows = questions
  .map((x) => `  (${q(x.id)}, ${q(x.category)}, ${q(x.textAr)}, true)`)
  .join(',\n');

const sql = `-- Generated by scripts/generate-seed.mjs — do not edit by hand.
-- Seeds the 30 characters and the predefined question list.

insert into public.characters (
  id, slug, name, gender, profession, profession_ar, field, skin_tone, hair_color,
  hair_length, hair_style, has_glasses, beard_style, headwear, clothing, uniform,
  accessory, works_in_office, works_outdoors, accent, visual_traits, image_url, active
) values
${characterRows}
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, gender = excluded.gender,
  profession = excluded.profession, profession_ar = excluded.profession_ar,
  field = excluded.field, skin_tone = excluded.skin_tone, hair_color = excluded.hair_color,
  hair_length = excluded.hair_length, hair_style = excluded.hair_style,
  has_glasses = excluded.has_glasses, beard_style = excluded.beard_style,
  headwear = excluded.headwear, clothing = excluded.clothing, uniform = excluded.uniform,
  accessory = excluded.accessory, works_in_office = excluded.works_in_office,
  works_outdoors = excluded.works_outdoors, accent = excluded.accent,
  visual_traits = excluded.visual_traits, image_url = excluded.image_url,
  active = excluded.active;

insert into public.questions (id, category, text_ar, active) values
${questionRows}
on conflict (id) do update set
  category = excluded.category, text_ar = excluded.text_ar, active = excluded.active;
`;

writeFileSync(join(root, 'supabase', 'seed.sql'), sql);
console.log(`Wrote supabase/seed.sql (${characters.length} characters, ${questions.length} questions)`);
